"""users, refresh_tokens (ERD v1 §3.1·§3.2)

Revision ID: 0001_users_refresh_tokens
Revises:
Create Date: 2026-09-05

손으로 작성했다. JWT 골격이 참조하는 두 테이블만 만든다.
나머지 테이블은 2주차 ERD 확정 후 autogenerate → 검토 순서로 추가한다.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_users_refresh_tokens"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 모델의 `BigIntPK` 와 같은 타입 (app/db/base.py).
#
# PostgreSQL 출력은 지금과 똑같다 — `BIGINT GENERATED BY DEFAULT AS IDENTITY`.
# 달라지는 건 SQLite 뿐이고, 거기서는 `INTEGER PRIMARY KEY` 여야 rowid 별칭이 되어
# 자동 증가가 동작한다. BIGINT 로 두면 마이그레이션은 통과하지만 첫 INSERT 가
# `NOT NULL constraint failed` 로 죽는다. Docker 없이 SQLite 로 띄울 때 걸리는 함정이다.
BIGINT = sa.BigInteger().with_variant(sa.Integer(), "sqlite")



def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("user_id", BIGINT, sa.Identity(always=False), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=30), nullable=False),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("day_start_hour", sa.SmallInteger(), server_default="4", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        # naming_convention 이 ck_users_ 접두를 붙인다 → ck_users_day_start_hour
        sa.CheckConstraint("day_start_hour BETWEEN 0 AND 23", name="day_start_hour"),
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", BIGINT, sa.Identity(always=False), nullable=False),
        sa.Column("user_id", BIGINT, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", BIGINT, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("token_id", name="pk_refresh_tokens"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="fk_refresh_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("users")
